# this dockerfile builds kitchen sync and runs the test suite.  it needs to be built with the project repo root as the buildroot.
# note that the tests are run as part of the build, you don't need to run anything afterwards.

FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		build-essential cmake libssl-dev \
		git ruby ruby-dev software-properties-common dirmngr gpg-agent && \
	apt-get clean -y && \
	rm -rf /var/cache/apt/archives/*

RUN DEBIAN_FRONTEND=noninteractive apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 7FCC7D46ACCC4CF8 && \
	DEBIAN_FRONTEND=noninteractive add-apt-repository 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main 12' && \
	DEBIAN_FRONTEND=noninteractive apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		postgresql-12 postgresql-client-12 libpq-dev && \
	apt-get clean -y && \
	rm -rf /var/cache/apt/archives/*

RUN gem install bundler -v 2.3.1 --no-ri --no-rdoc

WORKDIR /tmp
COPY test/Gemfile Gemfile
COPY test/Gemfile.lock Gemfile.lock
RUN bundle config --global silence_root_warning 1 && bundle install --without mysql --path ~/gems

ADD CMakeLists.txt /tmp/CMakeLists.txt
ADD cmake /tmp/cmake/
ADD src /tmp/src/
ADD test/CMakeLists.txt test/*.cpp /tmp/test/

WORKDIR /tmp/build
ENV SKIP_POSTGIS=1
RUN cmake .. && make

ADD test /tmp/test
RUN echo 'starting postgresql' && \
		service postgresql start && \
	echo 'creating postgresql database' && \
		su postgres -c 'createdb --encoding unicode --template template0 ks_test' && \
	echo 'creating postgresql user' && \
		su postgres -c 'createuser --superuser root' && \
	echo 'installing test gems' && \
		BUNDLE_GEMFILE=../test/Gemfile bundle install --without mysql --path ~/gems && \
	echo 'checking builds' && \
		ls -al /tmp/build && \
		psql -V && \
	echo 'running tests' && \
		CTEST_OUTPUT_ON_FAILURE=1 ENDPOINT_DATABASES=postgresql POSTGRESQL_DATABASE_USERNAME=root make test
