# this dockerfile builds kitchen sync and runs the test suite.  it needs to be built with the project repo root as the buildroot.
# note that the tests are run as part of the build, you don't need to run anything afterwards.

FROM centos:7

# we have to install Ruby from SCL because Centos 7 comes with an ancient version of Ruby 2.0 which segfaults in the mysql2 gem
RUN yum update -y && \
	yum clean all && \
	yum install -y centos-release-scl scl-utils && \
	yum install -y gcc gcc-c++ make cmake openssl-devel \
		postgresql-server postgresql-devel mariadb-server mariadb-devel \
		git rh-ruby25-ruby-devel

RUN scl enable rh-ruby25 -- gem install bundler -v 1.17.3 --no-ri --no-rdoc

WORKDIR /tmp
COPY test/Gemfile Gemfile
COPY test/Gemfile.lock Gemfile.lock
RUN scl enable rh-ruby25 -- bundle config --global silence_root_warning 1 && scl enable rh-ruby25 -- bundle install --path ~/gems

ADD CMakeLists.txt /tmp/CMakeLists.txt
ADD cmake /tmp/cmake/
ADD src /tmp/src/
ADD test/CMakeLists.txt test/*.cpp /tmp/test/

WORKDIR /tmp/build
ENV SKIP_POSTGIS=1
RUN cmake .. && make

ADD test /tmp/test
RUN echo 'creating postgresql database' && \
		su postgres -c "/usr/bin/pg_ctl -D /var/lib/pgsql/data init" && \
	echo 'starting postgresql' && \
		su postgres -c "/usr/bin/pg_ctl -D /var/lib/pgsql/data -w start" && \
	echo 'creating postgresql database' && \
		su postgres -c 'createdb --encoding unicode --template template0 ks_test' && \
	echo 'creating postgresql user' && \
		su postgres -c 'createuser --superuser root' && \
	echo 'creating mysql database' && \
		chown mysql:mysql /var/lib/mysql && \
		/usr/bin/mysql_install_db --user=mysql && \
	echo 'starting mysql' && \
		echo -e '[mysql]\nmax_allowed_packet=256M\n[mysqld]\nmax_allowed_packet=256M' >>/etc/my.cnf && \
		(/usr/bin/mysqld_safe --skip-grant-tables &) && \
	echo 'waiting for mysql to start' && \
		mysqladmin --wait=30 ping && \
	echo 'creating mysql database' && \
		mysqladmin create ks_test && \
	echo 'installing test gems' && \
		BUNDLE_GEMFILE=../test/Gemfile scl enable rh-ruby25 -- bundle install --path ~/gems && \
	echo 'checking builds' && \
		ls -al /tmp/build && \
		psql -V && \
		mysql -V && \
	echo 'running tests' && \
		CTEST_OUTPUT_ON_FAILURE=1 POSTGRESQL_DATABASE_USERNAME=root scl enable rh-ruby25 -- make test
