#define MSGPACK_POSITIVE_FIXNUM_MIN 0x00
#define MSGPACK_POSITIVE_FIXNUM_MAX 0x7f
#define MSGPACK_NEGATIVE_FIXNUM_MIN 0xe0
#define MSGPACK_NEGATIVE_FIXNUM_MAX 0xff
#define MSGPACK_FIXRAW_MIN          0xa0
#define MSGPACK_FIXRAW_MAX          0xbf
#define MSGPACK_FIXMAP_MIN          0x80
#define MSGPACK_FIXMAP_MAX          0x8f
#define MSGPACK_FIXARRAY_MIN        0x90
#define MSGPACK_FIXARRAY_MAX        0x9f
#define MSGPACK_NIL                 0xc0
#define MSGPACK_FALSE               0xc2
#define MSGPACK_TRUE                0xc3
#define MSGPACK_FLOAT               0xca
#define MSGPACK_DOUBLE              0xcb
#define MSGPACK_UINT8               0xcc
#define MSGPACK_UINT16              0xcd
#define MSGPACK_UINT32              0xce
#define MSGPACK_UINT64              0xcf
#define MSGPACK_INT8                0xd0
#define MSGPACK_INT16               0xd1
#define MSGPACK_INT32               0xd2
#define MSGPACK_INT64               0xd3
#define MSGPACK_RAW16               0xda
#define MSGPACK_RAW32               0xdb
#define MSGPACK_ARRAY16             0xdc
#define MSGPACK_ARRAY32             0xdd
#define MSGPACK_MAP16               0xde
#define MSGPACK_MAP32               0xdf
