#ifndef PROTOCOL_VERSIONS_H
#define PROTOCOL_VERSIONS_H

const int EARLIEST_PROTOCOL_VERSION_SUPPORTED = 7;
const int LATEST_PROTOCOL_VERSION_SUPPORTED = 8;

const int LAST_FILTERS_AFTER_SNAPSHOT_PROTOCOL_VERSION = 7;

#endif
