#ifndef PROTOCOL_VERSIONS_H
#define PROTOCOL_VERSIONS_H

const int EARLIEST_PROTOCOL_VERSION_SUPPORTED = 7;
const int LATEST_PROTOCOL_VERSION_SUPPORTED = 9;

const int LAST_FILTERS_AFTER_SNAPSHOT_PROTOCOL_VERSION = 7;
const int LAST_LEGACY_SCHEMA_FORMAT_VERSION = 7;
const int FIRST_IDLE_COMMAND_VERSION = 8;
const int FIRST_BLAKE3_VERSION = 9;

#endif
